### ISSUE TITLE
Exception raised: list index out of range

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#138]
An exception was encountered in [this session](https://transfer.sh/bSSYO/session.smh) using version f9a6a2f on Python 2.7.11 |Anaconda 4.0.0 (x86_64)| (default, Dec  6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)]:

``` python
Traceback (most recent call last):

  File "/Users/madelyncain/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 289, in mouseReleaseEvent
    guiEvent=event)

  File "/Users/madelyncain/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1926, in button_release_event
    self.callbacks.process(s, event)

  File "/Users/madelyncain/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)

  File "/Users/madelyncain/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)

  File "/Users/madelyncain/smhr/smh/gui/stellar_parameters.py", line 617, in figure_mouse_release
    self.spectrum_axis_mouse_release(event)

  File "/Users/madelyncain/smhr/smh/gui/stellar_parameters.py", line 773, in spectrum_axis_mouse_release
    spectral_model, proxy_index, index = self._get_selected_model(True)

  File "/Users/madelyncain/smhr/smh/gui/stellar_parameters.py", line 1242, in _get_selected_model
    proxy_index = self.table_view.selectionModel().selectedIndexes()[-1]

IndexError: list index out of range
```

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/t2enJ/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
This will be fixed with #261
