### ISSUE TITLE
Exception raised: Num lines returned 713 != 267 Num lines input

### ISSUE THREAD

**Issue by HonggeunKim** [andycasey/smhr#287]
An exception was encountered in [this session](https://transfer.sh/tK5jL/session.smh) using version None on Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  7 2017, 17:05:42) [GCC 7.2.0]:

````python
Traceback (most recent call last):

  File "/home/honggeun/smhr-0.2/smh/gui/stellar_parameters.py", line 664, in measure_abundances
    filtering=filtering)

  File "/home/honggeun/smhr-0.2/smh/session.py", line 879, in stellar_parameter_state
    self.stellar_photosphere, transitions[finite], twd=self.twd)

  File "/home/honggeun/smhr-0.2/smh/radiative_transfer/moog/cog.py", line 127, in abundance_cog
    raise RTError("Num lines returned {} != {} Num lines input".format(len(transitions_array),len(transitions)))

RTError: Num lines returned 713 != 267 Num lines input
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/1xR7s/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by HonggeunKim** [comment]
Hi Alex, I am sorry for bothering you with the same issue, but this is 
another error message that I met in different place.

The error message that I reported before happed when I pressed "Measure 
abundances", but this problem has been solved (it was because of the old 
version of MOOG). This "new" error message happened when I pressed 
"Measure all acceptable EW" in the Line Measurements tap. It is weird 
that I can measure the abundance of Fe I/II in the Stellar parameters 
tap, but cannot measure abundances of Fe I/II in the Line Measurements 
tap for the same data.

I've already tested several other observational data, and found smhr and 
MOOG work well without the problem for the data. I just reported this 
issue to ask some comments because I don't find any problem from MOOG. 
But you are right. MOOG may not be able to measure some lines in my 
data, so this is the problem of my data, though it is weird that I can 
still measure the abundances of Fe I/II in the Stellar parameters tap 
without any problem.


Thanks a lot for your help, and I am sorry for bothering you again.

Honggeun
