### ISSUE TITLE
Exception raised: 'vertices' must be a 2D list or array with shape Nx2

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#292]
An exception was encountered in [this session](https://transfer.sh/Y04bO/session.smh) using version e94df1f* on Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/gui/normalization.py", line 971, in update_order_figure
    self.draw_order(refresh=False)

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/gui/normalization.py", line 1091, in draw_order
    self.norm_plot.reset_zoom_limits()

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/gui/mpl.py", line 263, in reset_zoom_limits
    self.draw()

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/collections.py", line 911, in draw
    Collection.draw(self, renderer)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/collections.py", line 329, in draw
    mpath.Path(offsets), transOffset, tuple(facecolors[0]))

  File "/anaconda2/lib/python2.7/site-packages/matplotlib/path.py", line 135, in __init__
    "'vertices' must be a 2D list or array with shape Nx2")

ValueError: 'vertices' must be a 2D list or array with shape Nx2
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/Z9nae/screenshot.png)

**Additional details on how this exception occurred**:
Unsure whether same issue but it wont let me normalize the spectrum

**Comment by alexji** [comment]
Same as #291
