### ISSUE TITLE
Exception raised: f(a) and f(b) must have different signs

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#301]
An exception was encountered in [this session](https://transfer.sh/G1r76/session.smh) using version 12eec10 on Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/chemical_abundances.py", line 1386, in clicked_btn_find_upper_limit
    upper_limit = spectral_model.find_upper_limit(sigma=sigma, start_at_current=True)

  File "/Users/madelyncain/smhr-2/smhr/smh/spectral_models/synthesis.py", line 904, in find_upper_limit
    err = self.find_error(sigma=sigma, max_elem_diff=max_elem_diff, abundtol=tol, pix_per_element=pix_per_element)

  File "/Users/madelyncain/smhr-2/smhr/smh/spectral_models/synthesis.py", line 871, in find_error
    abund1 = op.brentq(minfn, abund0, abund0+max_elem_diff, xtol = abundtol)

  File "/Users/madelyncain/anaconda2/lib/python2.7/site-packages/scipy/optimize/zeros.py", line 510, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)

ValueError: f(a) and f(b) must have different signs
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/160cGE/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
This is not really an SMH error, but that the increased abundance (by 5 dex or something) is not enough to see the desired difference in chi2.

Before running the automatic upper limit finder, you need to first do a "best fit" to the non-line (i.e. set the continuum from which the upper limit will be calculated).
